EmpresasDeAnuncios/IKLAN/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('', include('pwa.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EmpresasDeAnuncios/app/urls.py
from django.db import router
from django.urls import include, path
from .views import agregar_producto, galeria, home, listar_productos,\
     modificar_producto, eliminar_producto, registro, ProductoViewset, MarcaViewset, error_facebook
from rest_framework import routers

router = routers.DefaultRouter()
router.register('producto', ProductoViewset)
router.register('marca', MarcaViewset)

urlpatterns = [
    path('', home, name='home'),
    path('galeria/', galeria, name='galeria'),
    path('agregar-producto/', agregar_producto, name='agregar_producto'),
    path('listar-producto/', listar_productos, name='listar_productos'),
    path('modificar-producto/<id>/', modificar_producto, name='modificar_producto'),
    path('eliminar-producto/<id>/', eliminar_producto, name='eliminar_producto'),
    path('registro/', registro, name='registro'),
    path('api/', include(router.urls)),
    path('error-facebook/', error_facebook, name="error_facebook"),
]

EmpresasDeAnuncios/app/models.py
from django.db import models

# Create your models here.
class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre= models.CharField(max_length=50)
    precio= models.IntegerField(null=True)
    descripción = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return self.nombre

EmpresasDeAnuncios/app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import fields_for_model
from django.shortcuts import redirect
from .models import Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .validators import MaxSizeFilevalidator
from django.forms import ValidationError


class ProductoForm(forms.ModelForm): 

    nombre = forms.CharField(min_length=3, max_length=50)
    imagen = forms.ImageField(required=False, validators=[MaxSizeFilevalidator(max_file_size=2)])
    precio = forms.IntegerField(required=False, min_value=1, max_value=15000000)

    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"]
        existe = Producto.objects.filter(nombre__iexact=nombre).exists()

        if existe:
            raise ValidationError("Este nombre ya existe")
        else:
            return nombre

    class Meta:
        model = Producto
        fields = '__all__'

        widgets = {
            "fecha_fabricacion": forms.SelectDateWidget()
        }

class CustomUserCreationFrom(UserCreationForm):
    

    class Meta:
        model = User
        fields = ['username', "first_name", "last_name", "email", "password1","password2"]

EmpresasDeAnuncios/app/views.py
from django.contrib.auth.password_validation import password_changed
from django.http.response import Http404
from django.shortcuts import get_object_or_404, render, redirect, get_list_or_404
from .models import Producto, Marca
from .forms import ProductoForm, CustomUserCreationFrom
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required
from rest_framework import serializers, viewsets
from .serializers import MarcaSerialize, ProductoSerializer
# Create your views here.

def error_facebook(request):
    return render(request, 'registration/error_facebook.html')

class MarcaViewset(viewsets.ModelViewSet):
    queryset= Marca.objects.all()
    serializer_class = MarcaSerialize

class ProductoViewset(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer

    def get_queryset(self):
        productos = Producto.objects.all()

        nombre = self.request.GET.get('nombre')
        
        if nombre:
            productos = productos.filter(nombre__contains=nombre)

        return productos

def home(request):
    productos = Producto.objects.all()
    data ={
        'productos': productos
    }
    return render(request, 'app/home.html', data)

#permiso para entrar a cualquier pesgtaña
#@login_required
def galeria(request):
    return render(request, 'app/galeria.html')

@permission_required('app.add_producto')
def agregar_producto(request):
    data = {
        'form' : ProductoForm()
    }
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto registrado")
            data["mensaje"] = "Se guardo correctamente"
        else:
            data["form"] = formulario

    return render(request, 'app/producto/agregar.html', data)

@permission_required('app.view_producto')
def listar_productos(request):
    productos = Producto.objects.all()
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(productos, 10)
        productos = paginator.page(page)
    except:
        raise Http404

    data = {
        'entity' : productos,
        'paginator': paginator
    }
    return render(request, 'app/producto/listar.html', data)

@permission_required('app.chage_producto')
def modificar_producto(request, id):
    
    producto = get_object_or_404(Producto, id=id)

    data = {
        'form': ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Se modifico correctamente")
            return redirect(to="listar_productos")
        data["form"] = formulario
    return render(request, 'app/producto/modificar.html', data)

@permission_required('app.delete_producto')
def eliminar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    messages.success(request, "Se elimino corectamente")
    return redirect(to="listar_productos")

def registro(request):
    data = {
        'form': CustomUserCreationFrom()
    }
    if request.method == 'POST':
        formulario = CustomUserCreationFrom(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, "Te has registrado correctamente")
            #refirigir al home
            return redirect(to="home")
        data["form"] = formulario
    return render(request, 'registration/registro.html', data)
 

EmpresasDeAnuncios/app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IKLAN</title>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap" rel="stylesheet">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    {% block css %} 
    {% endblock %}
    <link rel="stylesheet" href="{% static 'app/css/estilos.css' %}">
    {% load pwa %}
    {% progressive_web_app_meta %}
    
</head>
<body>

    <div id="principal">
        <header>
            <h1 id="h1principal">IKLAN</h1>
            <img  class="logo"  src="{% static 'app/img/logo.jpg' %}" alt="logo">            
        </header>
    </div>

        
        
        <div>
            <nav id="nav">
                <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    {% if perms.app.add_producto %}
                    <li><a href="{% url 'agregar_producto' %}">Agregar Producto</a></li>
                    {% endif %}
                    {% if perms.app.view_producto %}
                    <li><a href="{% url 'listar_productos' %}">Listado de Producto</a></li>
                    <li><a href="http://localhost:8000/admin/">Admin</a></li>

                    {% endif %}
                    {% if user.is_authenticated  %}
                    <li><a href="{% url 'logout' %}">Cerrar sesion</a></li>
                    <li><a href="#">{{ user.username}}</a></li>
                    <li>
                        {% for auth in backends.associated %}
                            {% if auth.provider == 'facebook' %}
                                <img src="{{ auth.extra_data.picture.data.url }}" alt="" width="50" height="50">
                            {% endif %}
                        {% endfor %}
                    </li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Iniciar sesion</a></li>
                    <li><a href="{% url 'registro' %}">Registrate</a></li>
                    {% endif %}
                </ul>
            </nav>

    </div>    

    <div id="contenido">

        {% block contenido %}
        {% endblock %}

    </div>

    <br><br><br>
    <footer>
        <div class="footer">
            <div class="footer1">
                <img src="{% static 'app/img/footer/new.png' %}" alt="balance">
            </div>

            <div class="footer1">
                <img src="{% static 'app/img/footer/puma.png' %}" alt="puma">
                
            </div>

            <div class="footer1">
                <img src="{% static 'app/img/footer/fila.png' %}" alt="fila">
                
            </div>

            <div class="footer1">
                <img src="{% static 'app/img/footer/nike.png' %}" alt="nike">
                
            </div>
            <div class="footer1">
                <img src="{% static 'app/img/footer/adidas.png' %}" alt="adidas">
            </div>
       
            <div class="footer1">
                <a id="footerTITULO">NOVEDADES</a>
                <a>Día din IVA</a>
                <a href="#">Black Friday</a>
            </div>

            <div class="footer1">
                <a id="footerTITULO">ASISTENCIA</a>
                <a href="#">Servicio al cliente</a>
                <a href="#">Preguntas frecuentes</a>
            </div>

            <div class="footer1">
                <a id="footerTITULO">TÉRMINOS Y CONDICIONES</a>
                <a href="#">Política de Privacidad</a>
                <a href="#">Aviso de Privacidad</a>
        </div>
        <div class="footerredes">
            <div class="footer1">
                <a href="https://www.facebook.com/TENIS-TENIS-104060735272582/?ref=pages_you_manage"><img src="{% static 'app/img/footer/facebook.png' %}" alt="puma"></a>
            </div>

            <div class="footer1">
                <a href="https://www.instagram.com/_tenisytenis_/"><img src="{% static 'app/img/footer/instagram.png' %}" alt="fila"></a>
            </div>

            <div class="footer1">
                <a href="https://www.youtube.com/channel/UCXn4FMj4jgR6C-2OuO0u0jQ"><img src="{% static 'app/img/footer/youtube.png' %}" alt="fila"></a>

            </div>

        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
    
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% block mesajeria %}
        {% if messages %}
            {% for m in messages %}
                <script>
                    Swal.fire({
                        "title": "Felicitaciones",
                        "text": "{{m}}",
                        "icon": "success"
                    })
                </script>
            {% endfor %}
        {% endif %}
    {% endblock %}
    {% block js %} 
    {% endblock %}

</body>
</html>

EmpresasDeAnuncios/app/templates/app/home.html
{% extends 'app/base.html' %}

{% load static %} 

{% block js %} 
<script src="{% static 'app/js/menu.js' %}"></script>
<script>
    $(document).ready(function() {
      $('.slider').bxSlider({
          mode: 'fade',//horizontal, vertical, fade
          auto: true,
          pause: 2000
      });
    });
</script>
{% endblock %}

{% block css %} 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
{% endblock %}

{% block contenido %} 

<br>
<div class="slider">
    <div>
        <img src="{% static 'app/img/banner/banner.png' %}" alt="">
    </div>
    <div>
        <img src="{% static 'app/img/banner/banner1.png' %}" alt="">
    </div>
    <div>
        <img src="{% static 'app/img/banner/banner2.png' %}" alt="">
    </div>
    <div>
        <img src="{% static 'app/img/banner/banner3.png' %}" alt="">
    </div>
</div>
{% load humanize %}
<h1>ANUNCIOS</h1>
<div class="productos">    
    {% for p in productos %}
        <div class="producto">

        <div class="contenedor_producto">
            {% if p.imagen %}
            <img src="{{ p.imagen.url }}" alt="imagen producto">
            {% endif %}
            <div class="detalle">
                {% if p.precio %}
                <h3>${{ p.precio | intcomma }}</h3>
                {% endif %}
                <h5>{{ p.marca | capfirst }}</h5>
                <h2>{{ p.nombre | title }}</h2>
                <h3>{{ p.descripción }}</h3>

            </div>

        </div>    
    </div>
    {% endfor %}

</div>

{% endblock %}

EmpresasDeAnuncios/app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

EmpresasDeAnuncios/app/templates/app/producto/agregar.html
{% extends 'app/base.html' %}

{% block contenido %} 


{% load crispy_forms_tags %}
<body id="imagenFormularios">
<br><br>
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="cardProductoNuevo">    
                    <div class="card-body">
                        <h2 id="LosFormularios">Nuevo Producto</h2>
                        <hr>
                        <form action="" method="post" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form | crispy }}
                            
                            <br>
                                <div class="productoNuevo">
                                    <input type="submit" value="Guardar" class="btn btn-primary-Guardar">
                                </div>
                                <br>                        
                                <div class="cancelarProducto">
                                    <input type="reset" value="Cancelar" class="btn btn-secondary-Cancelar">
                                    &nbsp;
                                </div>
                    </form>
                    {{mensaje}}

            </div>
        </div>
        <br><br>
    </div>
</div>
</body>

{% endblock %}

EmpresasDeAnuncios/app/templates/app/producto/listar.html
{% extends 'app/base.html' %}

{% block js %}

<script>
    function eliminarProducto(id) {
        Swal.fire({
            "title": "¿Estas seguro?",
            "text":"Esta acción no se puede deshacer",
            "icon": "question",
            "showCancelButton":true,
            "cancelButtonText":"No, Cancelar",
            "confirmButtonText":"Si, Eliminar",
            "reverseButtons":true,
            "confirmButtonColor":"#dc3545"
        })
        .then(function(result) {
            if(result.isConfirmed){
                window.location.href = "/eliminar-producto/"+id+"/"
            }
        })
    }
</script>
   
{% endblock %}

{% block contenido %} 
{% load humanize %}
<body id="imagenFormularios">
<br><br><br><br>
<div class="cardListado">
    <div class="card-body">
            <h2 id="LosFormularios">Listado de productos</h2>    
        <table class="table table-striped table-hover table-responsive-sm">
            <tr id="listaProducto">
                <hr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Marca</th>
                <th>Importado</th>
                <th>Opciones</th>
            </tr>
        
            {% for p in entity %}
        
            <tr>
                <td>{{ p.nombre | title }}</td>
                <td>${{ p.precio | intcomma }}</td>
                <td>{{ p.marca | title }}</td>
                <td>
                    {% if p.nuevo %}
                    SI
                    {% else %}
                    NO
                    {% endif %}
                </td>
                <td>
                    {% if perms.app.change_producto %}
                    <a href="{% url 'modificar_producto' p.id %}"><img src="../static/app/img/editar.png"></a>
                    {% endif %}
                    {% if perms.app.delete_producto %}
                    <a href="#" onclick="eliminarProducto({{ p.id }})"><img src="../static/app/img/eliminar.png"></a> 
                    {% endif %}
                </td>
            </tr>
          
        
            {% endfor %}
        
        </table>
        <hr>
        <div>
            {% include 'app/paginator.html'  %}
        </div>
    </div>
</div>
<br><br>
</body>
{% endblock %}

EmpresasDeAnuncios/app/templates/app/producto/modificar.html
{% extends 'app/base.html' %}

{% block contenido %} 


{% load crispy_forms_tags %}
<body id="imagenFormularios">
<br><br>
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="cardModificar">    
                    <div class="card-body">
                        <h2 id="LosFormularios">Editar producto</h2>
                        <hr>
                        <form action="" method="post" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form | crispy }}

                            <br>
                            <div class="modificarProducto">
                                <input type="submit" value="Editar" class="btn btn-primary-modificar-guar">
                            </div>

                            <br>

                            <div class="canceModifiProducto">
                                <input type="reset" value="Cancelar" class="btn btn-secondary-modificas-cance">
                                &nbsp;
                            </div>
                            

                    </form>
                    {{mensaje}}

                    </div>
                </div>
            </div>
        </div>
        <br><br>
</body>

{% endblock %}

EmpresasDeAnuncios/app/templates/offline.html
{% extends 'app/base.html' %}

{% block contenido %}

<h2>No tienes internet, favor revisa tu conexión</h2>

{% endblock %}